### PR TITLE
Update to Mediawiki 1.37 with federated properties

### PR DESCRIPTION
**Pull request by deer-wmde**
https://phabricator.wikimedia.org/T296176

Important non-bvious things that happen in this PR:
- wikibase code source comes from a tarball

Background: in order to use a non-released version of Wikibase with federated properties v2 related features, we took the code provided by the build artifacts from this build: https://github.com/wmde/wikibase-release-pipeline/actions/runs/1495123401

### CODE REVIEW

**Review by jakobw — COMMENTED** [review]
Yay feddy props!! \o/
Screenshot from 2021-11-29 15-43-13

I'm not sure I fully understand why Wikibase was included as a tarball though. Couldn't we just include it from codeload.github.com with the respective commit hash, just like the other extensions?

**Comment by deer-wmde** [comment]
> I'm not sure I fully understand why Wikibase was included as a tarball though. Couldn't we just include it from codeload.github.com with the respective commit hash, just like the other extensions?

great question! IIRC we went for this tarball approach so we could mostly use the script `mediawiki/wbstack/sync/02-fetch.sh` as it was, I remember hearing about some troubles with submodules. Feel free to correct me @tarrow and @addshore

**Comment by jakobw** [comment]
> great question! IIRC we went for this tarball approach so we could mostly use the script `mediawiki/wbstack/sync/02-fetch.sh` as it was, I remember hearing about some troubles with submodules. Feel free to correct me @tarrow and @addshore

Ahh, because we're not downloading a git repo but just the zipped source files, so we can't just initialize the sub modules. Makes sense. Ughh, I don't like it but also don't have a better idea off the top of my head :)

**Review by jakobw — APPROVED** [review]
Works! \o/

**Comment by addshore** [comment]
> Ahh, because we're not downloading a git repo but just the zipped source files, so we can't just initialize the sub modules. Makes sense. Ughh, I don't like it but also don't have a better idea off the top of my head :)

Indeed.
Personally I don't really like included the tar file here in this git repo either.
I feel we should store this file in some other artefact repo / location and refer to it by URL (similar to the other archives).

I don't think this is a pattern that we would want to continue, as it will dramatically increase the size of this repository etc.
The TLDR of this thinking can be roughly seen at https://vegeta2102.medium.com/why-you-should-not-push-binary-files-to-git-and-what-to-do-if-you-do-29f34692cef0

From that post:
> First you need to remember that Git can not diff birnay file. It will upload entiry file into repository and will store its pretty much forever.
> It will also store every single version of every single binary file within the repository. So , if you clone that repository, you’ll need download all of them, all of version of that binary file. So that will make cloning repository become as slow as tortoise.

Right now the possible options I would see for us if we wanted to do that would be 1) some google cloud bucket? 2) some other git repo that isnt this one? 3) something else?

**Comment by addshore** [comment]
https://github.com/wbstack/mediawiki-tars
https://github.com/wbstack/mediawiki-tars/raw/main/wikibase-feddy-props-1668.tar.gz

**Comment by tarrow** [comment]
So the conclusion was that perhaps the least contentious thing was to create another repository to store this tarball in. Naturally this comes with the maintenance overhead of another repository

Possible alternatives were:
- keeping the Wikibase code unchanged by the sync scripts and manually maintaining it
- maintaining an uncompressed copy of the Wikibase code in this repo and copying it into place
- just keeping the tar in repo and accepting that this is a pattern that is unsustainable in the long run

**Pull request merged**
