### PR TITLE
Add a triggerable workflow for running and commiting sync

### PR DESCRIPTION
**Pull request by addshore**
Not tested yet, but in principle the sync already works, as
we have a job that runs a diff to disallow merging.
So as long as the commit action works this should work.

I wrote this as I am using mobile data and don't want to run
it all locally...

### CODE REVIEW

**Comment by addshore** [comment]
I would plan on running this on https://github.com/wbstack/mediawiki/pull/276

**Comment by tarrow** [comment]
Like the concept but not sure I love the implementation. I would feel more confident if this opened a PR (even to `not-main`) and then we manually merged it

**Comment by addshore** [comment]
> Like the concept but not sure I love the implementation. I would feel more confident if this opened a PR (even to `not-main`) and then we manually merged it

Shouldn't be too hard to rework it to do that!
I'll take a look

**Comment by addshore** [comment]
per the comment in the file, a permission is needed to create PRs, but this is already enabled on this repository

**Review by tarrow — APPROVED** [review]

**Comment by tarrow** [comment]
Seems like the easiest way to test this is to merge it... let's go ahead

**Comment by tarrow** [comment]
Seems like the easiest way to test this is to merge it... let's go ahead

**Comment by addshore** [comment]
Happy to report success https://github.com/wbstack/mediawiki/pull/278

**Pull request merged**
