### PR TITLE
Update pacman + dist with latest changes from REL1_37 

### PR DESCRIPTION
**Pull request by toban**
https://phabricator.wikimedia.org/T315594

### CODE REVIEW

**Comment by deer-wmde** [comment]
It's really hard to see the relevant changes but I think it's these two files?
https://github.com/wbstack/mediawiki/blob/c8216278db549c4691c2b153e8d8858a38d5578f/dist/extensions/StopForumSpam/includes/DenyListManager.php

https://github.com/wbstack/mediawiki/blob/c8216278db549c4691c2b153e8d8858a38d5578f/dist/extensions/StopForumSpam/includes/Hooks.php

Anyway, I tried it locally and it's way faster now and I don't get 502s anymore, even with 5 scripts running simultaneously adding items for half an hour :star_struck:

**Review by deer-wmde — APPROVED** [review]

**Comment by deer-wmde** [comment]
I guess we want to update the files in `dist-persist` as well? tbh I don't fully understand it's purpose

**Comment by addshore** [comment]
> I guess we want to update the files in `dist-persist` as well? tbh I don't fully understand it's purpose

Regarding dist-persist, I updated the docs https://github.com/wbstack/mediawiki/pull/273
This directory only needs updating if files within it need changing.
This PR doesnt change any of those files.

PR looks good to me!

**Review by addshore — APPROVED** [review]
Could perhaps do with a more informative PR title

**Pull request merged**
