### PR TITLE
Disable db replication locally

### PR DESCRIPTION
**Pull request by toban**

### CODE REVIEW

**Comment by toban** [comment]
Hmm, this is really annoying locally but doesn't seem to pass in GH actions since redis is reading the database?

Not really sure what the best way forward is?

- Copy paste replication code from [Mediawiki-docker-dev](https://github.com/addshore/mediawiki-docker-dev/blob/master/docker-compose.yml#L14)?
- Add some kind of `DEV` flag we can switch this `localhost` to instead?

**Comment by addshore** [comment]
I suspect the issues is this cache, https://github.com/wbstack/mediawiki/blob/39b255ccde8785154f2c421951996bd60719e3f8/wbstack/src/Settings/ProductionCache.php#L58-L80
Which ONLY reads from the SQL replicas, and thus will probably not work if there is no replica.

**Comment by addshore** [comment]
This (well the oposite) is also being worked on at https://github.com/wbstack/mediawiki/pull/101 which adds replication to the setup

**Comment by toban** [comment]
> This (well the oposite) is also being worked on at #101 which adds replication to the setup

Nice lets go that route instead!

**Pull request closed without merging**
