### PR TITLE
Update to MediaWiki 1.39

### PR DESCRIPTION
**Pull request by AndrewKostka**

### CODE REVIEW

**Comment by deer-wmde** [comment]
great catch with StopForumSpam!

**Review by m90 — APPROVED** [review]
Built and tested this successfully on my end.

**Comment by tarrow** [comment]
Cool; lets merge and then we'll have a candidate image that we can try on staging :)

**Comment by deer-wmde** [comment]
What works for me with this image:
- [x] running a 1.38 wiki
  - [x] creating, updating items and statements
  - [x] using the query service

What does not work for me:
- [ ] Upgrading a 1.38 wiki via dispatching a MediawikiUpdate Job ([logs](https://phabricator.wikimedia.org/P45952))
- [ ] OAuth for e.g. QuickStatements ([logs](https://phabricator.wikimedia.org/P45953))

**Comment by m90** [comment]
> Upgrading a 1.38 wiki via dispatching a MediawikiUpdate Job

I was under the impression this is expected as you would need an up to date api for it (which does not exist yet)

> OAuth for e.g. QuickStatements

Did you update configuration accordingly? I've seen the exact same error in staging before we merged https://github.com/wmde/wbaas-deploy/pull/797 but it went away with that fix

**Comment by m90** [comment]
I'll merge this so I can cut an early morning image. If the issues do show up in staging as well, we can always come back and look into these.

**Comment by deer-wmde** [comment]
> > Upgrading a 1.38 wiki via dispatching a MediawikiUpdate Job
> 
> I was under the impression this is expected as you would need an up to date api for it (which does not exist yet)
> 
> > OAuth for e.g. QuickStatements
> 
> Did you update configuration accordingly? I've seen the exact same error in staging before we merged [wmde/wbaas-deploy#797](https://github.com/wmde/wbaas-deploy/pull/797) but it went away with that fix

Yeah I think both my points can be ignored, I didn't point the OAuth services to the new deployment and yeah the api is not ready yet. It was getting late for me... :D

**Pull request merged**
